# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "model.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0bmodel.proto\x12\x05model"(\n\x0ePredictRequest\x12\n\n\x02x1\x18\x01 \x01(\x02\x12\n\n\x02x2\x18\x02 \x01(\x02"!\n\x0fPredictResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32H\n\x0cModelService\x12\x38\n\x07Predict\x12\x15.model.PredictRequest\x1a\x16.model.PredictResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "model_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PREDICTREQUEST"]._serialized_start = 22
    _globals["_PREDICTREQUEST"]._serialized_end = 62
    _globals["_PREDICTRESPONSE"]._serialized_start = 64
    _globals["_PREDICTRESPONSE"]._serialized_end = 97
    _globals["_MODELSERVICE"]._serialized_start = 99
    _globals["_MODELSERVICE"]._serialized_end = 171
# @@protoc_insertion_point(module_scope)
