"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import typing

import google.protobuf.descriptor
import google.protobuf.message

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class PredictRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    X1_FIELD_NUMBER: builtins.int
    X2_FIELD_NUMBER: builtins.int
    x1: builtins.float
    x2: builtins.float
    def __init__(
        self,
        *,
        x1: builtins.float = ...,
        x2: builtins.float = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing.Literal["x1", b"x1", "x2", b"x2"]
    ) -> None: ...

global___PredictRequest = PredictRequest

@typing.final
class PredictResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RESULT_FIELD_NUMBER: builtins.int
    result: builtins.float
    def __init__(
        self,
        *,
        result: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["result", b"result"]) -> None: ...

global___PredictResponse = PredictResponse
